name: Rust

on:
  workflow_dispatch:
permissions:
  contents: write
env:
  LANG: en_US.UTF-8
jobs:
  build:
    name: deploy
    runs-on: ubuntu-18.04
    container: himanshumps/ubi7_container
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: himanshumps/rust-musl-action@master
        with:
          args: cargo +stable build --release

      - name: Package
        shell: bash
        run: |
          ls -altr target/release
          cd target/release          
          tar czvf ../../jni_test-${{ matrix.target }}.tar.gz *
          cd -
      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
      - name: Publish
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name:  ${{ steps.tag.outputs.release_tag }}
            files: 'jni_test*.*'
