name: Rust

on:
  workflow_dispatch:

env:
  LANG: en_US.UTF-8
jobs:
  build:
    name: deploy
    runs-on: ubuntu-18.04
    strategy: 
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: complete
          override: true
          target: ${{ matrix.target }}
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          #strip target/${{ matrix.target }}/release/testmest
          cd target/${{ matrix.target }}/release          
          tar czvf ../../../testmest-${{ matrix.target }}.tar.gz jni_test
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        # TODO: if any of the build step fails, the release should be deleted.
        with:
            files: 'jni_test*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
